### ISSUE TITLE
Setcap not available on MacOS

### ISSUE THREAD

**Issue by gonzonia** [AMoo-Miki/homebridge-switchmate-ble#15]
I can't do the setup with "sudo setcap 'cap_net_raw,cap_net_admin+eip' `which node`" 
because that command won't work on MacOS. Any suggestions for a workaround?

I tried just installing and running switchmate-ble find
This is the result
```
/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/scanner.js:28
        noble._bindings._hci.on('leScanEnableSetCmd', enabled => {
                             ^

TypeError: Cannot read property 'on' of undefined
    at new Scanner (/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/scanner.js:28:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/scanner.js:224:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate-ble/bin/cli-find.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**Comment by AMoo-Miki** [comment]
I looked into [node-bluetooth-hci-socket](https://github.com/noble/node-bluetooth-hci-socket) which is responsible for `noble._bindings._hci` and sadly, it is not compatible with OSX. I have updated the Readme to indicate this.
