### ISSUE TITLE
Errors when using Homebridge 1.3.x

### ISSUE THREAD

**Issue by tgpatrick** [AMoo-Miki/homebridge-switchmate-ble#16]
I've been getting a couple errors pretty often. Once it happens, it repeats every few minutes. This only happens on 1.2.x and 1.3.x; they don't appear when I roll back to 1.1.x.

[3/9/2021, 6:42:55 PM] [homebridge-switchmate-ble] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/9/2021, 6:43:21 PM] [homebridge-switchmate-ble] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received object. See https://git.io/JtMGR for more info.

**Comment by tgpatrick** [comment]
Here's the stack trace:

[3/10/2021, 8:49:50 PM] [homebridge-switchmate-ble] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/10/2021, 8:49:50 PM] [homebridge-switchmate-ble] Error: 
    at Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2032:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1661:22
    at Object.callback (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18)
    at /usr/lib/node_modules/homebridge-switchmate-ble/node_modules/async/dist/async.js:1311:26
    at /usr/lib/node_modules/homebridge-switchmate-ble/node_modules/async/dist/async.js:321:20
    at /usr/lib/node_modules/homebridge-switchmate-ble/lib/Switch3.js:224:50
    at /usr/lib/node_modules/homebridge-switchmate-ble/node_modules/async/dist/async.js:3811:21
    at /usr/lib/node_modules/homebridge-switchmate-ble/lib/Switch3.js:196:50
    at Timeout.retryAttempt [as _onTimeout] (/usr/lib/node_modules/homebridge-switchmate-ble/node_modules/async/dist/async.js:3804:13)
    at listOnTimeout (internal/timers.js:554:17)
