### ISSUE TITLE
Too Many Listeners

### ISSUE THREAD

**Issue by robbydek** [AMoo-Miki/homebridge-switchmate-ble#19]
(node:7075) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 characteristicsDiscover listeners added to [Service]. Use emitter.setMaxListeners() to increase limit

I think this has to be due to the number of devices that I have on my homebridge along with 5 switchmate devices (4 v3 switches and an outlet).
It appears to be affecting my ability to use my switchmate devices with HomeKit.

It looks like the number of listeners could be increased in the code to solve for this.

**Comment by robbydek** [comment]
I got an error now.  Here's the context:

(node:7075) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 characteristicsDiscover listeners added to [Service]. Use emitter.setMaxListeners() to increase limit
(node:7075) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 characteristicsDiscover listeners added to [Service]. Use emitter.setMaxListeners() to increase limit
(node:7075) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 characteristicsDiscover listeners added to [Service]. Use emitter.setMaxListeners() to increase limit
(node:7075) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 characteristicsDiscover listeners added to [Service]. Use emitter.setMaxListeners() to increase limit
(node:7075) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 characteristicsDiscover listeners added to [Service]. Use emitter.setMaxListeners() to increase limit
(node:7075) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 characteristicsDiscover listeners added to [Service]. Use emitter.setMaxListeners() to increase limit
[8/19/2021, 2:49:22 PM] TypeError: callback is not a function
    at Switch3.updateBatteryLevel (/usr/lib/node_modules/homebridge-switchmate-ble/lib/Switch3.js:164:52)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-switchmate-ble/lib/Switch3.js:168:18)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
