### ISSUE TITLE
Does this work on a Mac running Catalina?

### ISSUE THREAD

**Issue by bwalls** [AMoo-Miki/homebridge-switchmate-ble#5]
Definitely can't run 
sudo setcap 'cap_net_raw,cap_net_admin+eip' `which node`

Currently seeing:
[5/14/2020, 5:42:06 PM] ====================
[5/14/2020, 5:42:06 PM] ERROR LOADING PLUGIN homebridge-switchmate-ble:
[5/14/2020, 5:42:06 PM] TypeError: Cannot read property 'on' of undefined
    at new Scanner (/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/scanner.js:27:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/scanner.js:219:28)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/Switch1.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/SwitchAccessory.js:1:17)
[5/14/2020, 5:42:06 PM] ====================

**Comment by reedhaffner** [comment]
I'm having the same problem on MacOS High Sierra

**Comment by AMoo-Miki** [comment]
Without giving permission to `node` to control the Bluetooth radio, there is nothing this plugin can do.
